---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all 
  remote_user: user
  # remote_user: user
  become: yes
  become_method: sudo

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
